config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :demandes
  resources :diplomes
  devise_for :utilisateurs
  resources :articles
  devise_for :administrateurs
	  devise_scope :administrateur do
    get '/administrateurs/sign_out' => 'devise/sessions#destroy'
  end
  resources :etablissements
  resources :countries
  resources :accueil
  resources :categories
  root "accueil#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Votre message a été envoyé ! ' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:nom, :email, :telephone, :ville, :contenu)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= render 'menus/main' %>
<div class="container-fluid">
	<div class="row">
	<div class="col-lg-12  col-12 text-center ze-pad bg-white">
	      	      <h2 class="text-bold text-maj  entete">contactez-nous</h2>
	      </div>
		<div class="col-lg-6 offset-lg-3 col-12 contact-form m-top-mini m-bottom ze-pad">
 <%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-lg-12 col-12">
    <strong><%= form.label :nom %></strong>
    <%= form.text_field :nom, class:"form-control", placeholder:"Quel est votre nom?" %>
  </div>

  <div class="form-group col-lg-12 col-12">
    <strong><%= form.label :email %></strong>
    <%= form.text_field :email, class:"form-control", placeholder:"Via quel adresse e-mail souhaitez-vous être contacté?" %>
  </div>

  <div class="form-group col-lg-12 col-12">
    <strong><%= form.label :telephone %></strong>
    <%= form.text_field :telephone, class:"form-control", placeholder:"Via quel numéro de téléphone souhaitez-vous être contacté?" %>
  </div>

  <div class="form-group col-lg-12 col-12">
    <strong><%= form.label :ville %></strong>
    <%= form.text_field :ville, class:"form-control", placeholder:"Vous êtes dans quelle ville?" %>
  </div>

  <div class="form-group col-lg-12 col-12">
    <strong><%= form.label :Comment_pouvons_nous_vous_aider? %></strong>
    <%= form.text_area :contenu, class:"form-control", placeholder:"Quel est votre nom?" %>
  </div>

  <div class="form-group col-lg-12 col-12">
    <%= form.submit "Envoyer le message", class:"form-control btn btn-appel text-bold text-maj" %>
  </div>
<% end %>
</div>
	</div>
</div>
<%=render 'footers/main-footer'%>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Email</th>
      <th>Telephone</th>
      <th>Ville</th>
      <th>Contenu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.nom %></td>
        <td><%= message.email %></td>
        <td><%= message.telephone %></td>
        <td><%= message.ville %></td>
        <td><%= message.contenu %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<%= render 'form', message: @message %>

app/views/messages/show.html.erb
<%=render 'menus/main'%>
<div class="container-fluid">
	<div class="row">
	       <div class="col-lg-8 offset-lg-2 col-12   m-top m-bottom bg-white ze-pad">
<%if administrateur_signed_in?%>
<p>
  <strong>Nom:</strong>
  <%= @message.nom %>
</p>

<p>
  <strong>Email:</strong>
  <%= @message.email %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @message.telephone %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @message.ville %>
</p>

<p>
  <strong>Contenu:</strong>
  <%= raw(@message.contenu) %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>
<%else%>
<h4 class="text-center text-success" id="notice"><%= notice %></h4>
<% end %>
		</div>
	</div>
</div>
<%=render 'footers/main-footer'%>