config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :demandes
  resources :diplomes
  devise_for :utilisateurs
  resources :articles
  devise_for :administrateurs
	  devise_scope :administrateur do
    get '/administrateurs/sign_out' => 'devise/sessions#destroy'
  end
  resources :etablissements
  resources :countries
  resources :accueil
  resources :categories
  root "accueil#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :titre, use: :slugged
  mount_uploader :photo, PhotoUploader
  belongs_to :administrateur
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_administrateur!, except:[:index, :show]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
	@etablissements = Etablissement.all.limit(8)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
	  @etablissements = Etablissement.all.limit(8)
	  @articles = Article.all.limit(4)
  end

  # GET /articles/new
  def new
    @article = current_administrateur.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_administrateur.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:titre, :contenu, :photo, :administrateur_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titre %>
    <%= form.text_field :titre %>
  </div>

  <div class="field">
    <%= form.label :contenu %>
    <%= form.text_area :contenu %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render 'menus/main' %>
<div class="container-fluid bg-white">
	<div class="row">
	      	<div class="col-lg-12  col-12 text-center ze-pad bg-white">
	      	      <h2 class="text-bold text-maj  entete">guide des conseils</h2>
	      </div>
	</div>
</div>
<div class="container">
      <div class="row">
      	<div class="col-lg-12 col-12 bg-white m-top">
      		    <div class="row m-top">
					  <div class="col-lg-8 col-12 ze-pad">
					  	     <div class="row">
					  	     	     <%@articles.each do |article| %>
			      <div class="col-lg-6 col-6 mb-3">
			      	     <figure class="snip1312">
  <div class="image"><%=image_tag article.photo.url%></div>
  <figcaption>
    <h3><%=article.titre%></h3>
    <footer>
      <div class="views"><%=link_to "lire l'article", article, class:"nav-article"%></div>
    </footer>
  </figcaption><%=link_to "", article%>
</figure>
			      </div>
			<% end %>

					  	     </div>
					  </div>
					  
					  <div class="col-lg-3 offset-lg-1  col-12 m-top">
              	           <h6 class="text-bold text-maj ">Suivez-nous sur Facebook</h6>
               	           <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FUniverSkool-100392674770808%2F%3Fmodal%3Dadmin_todo_tour&tabs=timeline&width=340&height=222&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId=2372197659699611" width="100%" height="222" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
               	     
	               	          <h5 class="text-bold text-maj m-top">les écoles à la une</h5>
		               	       
			    	   	      
			    	   	      	      		<%@etablissements.each do |etablissement|%>
			    	   	      	      		<div class="card mb-3 m-top" style="max-width: 100%;">
  <div class="row no-gutters">
    <div class="col-md-3">
      <%=image_tag etablissement.profil.url,class:"card-img"%>
    </div>
    <div class="col-md-9">
      <div class="card-body">
               <h5 class="card-title text-bold text-maj">
                       <%=link_to etablissement do %>
                        <%=etablissement.nom%>
                        <% end%>
                </h5>
      </div>
    </div>
  </div>
</div>
<%end%>
			    	   	      
			    
		               </div>
					  
			    </div>
      	</div>
      </div>
</div>
<% if administrateur_signed_in?%>
<%= link_to 'New Article', new_article_path %>
<%else%>
<% end %>
<%=render 'footers/main-footer'%>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render 'menus/main' %>
<div class="container">
	<div class="row">
		<div class="col-lg-12 col-12 bg-white m-top">
			    <div class="row">
			    	   <div class="col-lg-8 col-12 m-top ze-pad">
	                         <h2 class="text-bold text-cap"><%= @article.titre %></h2>
		                      <div><%= image_tag @article.photo.url, class:"img-fluid m-top" %></div>
                              <p><%= raw(@article.contenu) %></p>
                              <div class="row">
                              	<div class="col-lg-12  col-12 m-top">
	               	          <h3 class="text-bold text-maj m-top">les autres conseils</h3>
	               	          <hr>
		               	       <div class="row">
		               	       <%@articles.each do |article|%>
		    	   	      	      		
                              	<div class="col-lg-6  col-12">
			    	   	      	      		<div class="card mb-3 m-top" style="max-width: 100%;">
  <div class="row no-gutters">
    <div class="col-md-6">
      <%=image_tag article.photo.url,class:"card-img"%>
    </div>
    <div class="col-md-6">
      <div class="card-body">
               <h5 class="card-title text-bold text-maj">
                       <%=link_to article do %>
                        <%=article.titre%>
                        <% end%>
                </h5>
      </div>
    </div>
  </div>
</div>
								  </div>
						   
<%end%>
			    	</div>   	      
			    
		               </div>
                              </div>
		               </div>
		               <div class="col-lg-3 offset-lg-1  col-12 m-top">
              	           <h6 class="text-bold text-maj m-top-big">Suivez-nous sur Facebook</h6>
               	           <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FUniverSkool-100392674770808%2F%3Fmodal%3Dadmin_todo_tour&tabs=timeline&width=340&height=222&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId=2372197659699611" width="100%" height="222" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
               	             
	               	          <h5 class="text-bold text-maj m-top">les écoles à la une</h5>
		               	       
			    	   	      
			    	   	      	      		<%@etablissements.each do |etablissement|%>
			    	   	      	      		<div class="card mb-3 m-top" style="max-width: 100%;">
  <div class="row no-gutters">
    <div class="col-md-3">
      <%=image_tag etablissement.profil.url,class:"card-img"%>
    </div>
    <div class="col-md-9">
      <div class="card-body">
               <h5 class="card-title text-bold text-maj">
                       <%=link_to etablissement do %>
                        <%=etablissement.nom%>
                        <% end%>
                </h5>
      </div>
    </div>
  </div>
</div>
<%end%>
			    	   	      
			    
		               </div>
			    </div>
		</div>
	</div>
</div>
<%if administrateur_signed_in?%>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>
<% else %>
<% end %>
<%=render 'footers/main-footer'%>