config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :demandes
  resources :diplomes
  devise_for :utilisateurs
  resources :articles
  devise_for :administrateurs
	  devise_scope :administrateur do
    get '/administrateurs/sign_out' => 'devise/sessions#destroy'
  end
  resources :etablissements
  resources :countries
  resources :accueil
  resources :categories
  root "accueil#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/demande.rb
class Demande < ApplicationRecord
	extend FriendlyId
  friendly_id :objet, use: :slugged
end

app/controllers/demandes_controller.rb
class DemandesController < ApplicationController
  before_action :set_demande, only: [:show, :edit, :update, :destroy]

  # GET /demandes
  # GET /demandes.json
  def index
    @demandes = Demande.all
  end

  # GET /demandes/1
  # GET /demandes/1.json
  def show
  end

  # GET /demandes/new
  def new
    @demande = Demande.new
  end

  # GET /demandes/1/edit
  def edit
  end

  # POST /demandes
  # POST /demandes.json
  def create
    @demande = Demande.new(demande_params)

    respond_to do |format|
      if @demande.save
        format.html { redirect_to @demande, notice: 'Votre demande a été envoyée !' }
        format.json { render :show, status: :created, location: @demande }
      else
        format.html { render :new }
        format.json { render json: @demande.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demandes/1
  # PATCH/PUT /demandes/1.json
  def update
    respond_to do |format|
      if @demande.update(demande_params)
        format.html { redirect_to @demande, notice: 'Demande was successfully updated.' }
        format.json { render :show, status: :ok, location: @demande }
      else
        format.html { render :edit }
        format.json { render json: @demande.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demandes/1
  # DELETE /demandes/1.json
  def destroy
    @demande.destroy
    respond_to do |format|
      format.html { redirect_to demandes_url, notice: 'Demande was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demande
      @demande = Demande.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demande_params
      params.require(:demande).permit(:nom, :telephone, :email, :objet, :contenu)
    end
end

app/helpers/demandes_helper.rb
module DemandesHelper
end

app/views/demandes/_form.html.erb
		<div class="m-top-mini m-bottom">
				    <%= form_for @demande  do |form| %>
				    <div class="row">
  <div class="form-group col-lg-6 col-12">
    <%= form.label :nom %> *
    <%= form.text_field :nom, class:"form-control", required: true %>
  </div>

  <div class="form-group col-lg-6 col-12">
    <%= form.label :telephone %> *
    <%= form.text_field :telephone, class:"form-control", required: true %>
  </div>

  <div class="form-group col-lg-6 col-12">
    <%= form.label :email %> *
    <%= form.text_field :email, class:"form-control", required: true %>
  </div>

  <div class="form-group col-lg-6 col-12">
    <%= form.label :ecole %> *
    <%= form.text_field :objet, value: @etablissement.nom, class:"form-control", required: true, readonly: true %>
  </div>

  <div class="form-group col-lg-12 col-12">
    <%= form.label :Votre_demande %>
    <%= form.text_area :contenu, cols: "50", rows: "30", required: true%>
  </div>

  <div class="form-group col-lg-12 col-12">
    <%= form.submit "Confirmer la Pré-inscription", class:"btn btn-appel text-bold text-maj" %>
  </div>
  	</div>
<% end %>

		
		</div>

app/views/demandes/_new.html.erb
<h1>New Demande</h1>

<%= render 'form', demande: @demande %>

<%= link_to 'Back', demandes_path %>

app/views/demandes/edit.html.erb
<h1>Editing Demande</h1>

<%= render 'form', demande: @demande %>

<%= link_to 'Show', @demande %> |
<%= link_to 'Back', demandes_path %>

app/views/demandes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Demandes</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Telephone</th>
      <th>Email</th>
      <th>Objet</th>
      <th>Contenu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @demandes.each do |demande| %>
      <tr>
        <td><%= demande.nom %></td>
        <td><%= demande.telephone %></td>
        <td><%= demande.email %></td>
        <td><%= demande.objet %></td>
        <td><%= demande.contenu %></td>
        <td><%= link_to 'Show', demande %></td>
        <td><%= link_to 'Edit', edit_demande_path(demande) %></td>
        <td><%= link_to 'Destroy', demande, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Demande', new_demande_path %>

app/views/demandes/show.html.erb
<%= render 'menus/main' %>
<div class="container">
	<div class="row">
		<div class="col-lg-8 offset-lg-2 col-12 bg-white m-top m-bottom ze-pad">
<p class="text-success m-top" role="alert" id="notice"><%= notice %></p>
<p>
  <strong>Nom:</strong>
  <%= @demande.nom %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @demande.telephone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @demande.email %>
</p>

<p>
  <strong class="text-cap">école choisie:</strong>
  <%= @demande.objet %>
</p>

<p>
  <strong>Demande:</strong>
</p>
<p>
  <%= raw(@demande.contenu) %>
</p>
<%if administrateur_signed_in?%>
<%= link_to 'Edit', edit_demande_path(@demande) %> |
<%= link_to 'Back', demandes_path %>
<%else%>
<%end%>
		</div>
	</div>
</div>
<%=render 'footers/main-footer'%>